on:
  push:
    branches:
      - main
      - 13-feat-implement-automatic-version-updates
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - run: pnpm install

      - name: Run unit tests
        run: pnpm run test

      - name: Build the project
        run: pnpm run build

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
